config/routes.rb
Theodinproject::Application.routes.draw do
devise_for :users, 
  :controllers => { :registrations => "registrations", 
    :omniauth_callbacks => "omniauth_callbacks",
    :confirmations => "confirmations" }
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy', :method => :delete
    get 'sign_up' => 'devise/registrations#new'
    get 'signup' => 'devise/registrations#new'
    get '/confirm_email' => 'users#send_confirmation_link'
  end

  root :to => 'static_pages#home'
  get 'home' => 'static_pages#home'
  get 'scheduler' => redirect('/courses')
  post 'thank_you' => 'static_pages#send_feedback'
  post 'suggestion' => 'static_pages#suggestion'
  get 'students' => 'users#index'
  get 'about' => "static_pages#about"
  get 'faq' => "static_pages#faq"
  get 'contact' => "static_pages#contact"
  get 'contributing' => "static_pages#contributing"
  get 'studygroup' => redirect('/studygroups')
  get 'legal' => "static_pages#legal"
  get 'cla' => "static_pages#cla"
  get 'tou' => "static_pages#tou"
  get 'press' => redirect('https://docs.google.com/document/d/1FmjfYvOsQ-syoOCzuvPXv96TCxeJAT9m-Wl7trgNZcE/pub')
  get 'studygroups' => "static_pages#studygroups"

  #failure route if github information returns invalid
  get '/auth/failure' => 'omniauth_callbacks#failure'


  resources :cal_events

  # This is being hidden until needed (it was needed by the scheduler
  # but that got killed but will still be useful later)
  # resource :user_pref, :only => [:edit, :update]

  resources :users, :only => [:show, :index, :edit, :update] do
    resource :contact, :only => [:new, :create]
  end

  resources :splash_emails, :only => [:create]

  resource :forum, :only => [:show]

  post 'lesson_completions' => 'lesson_completions#create'
  delete 'lesson_completions/:lesson_id' => 'lesson_completions#destroy', :as => "lesson_completion"

  # Sitemap
  get "sitemap" => "sitemap#index", :defaults => { :format => "xml" }

  # ***** COURSES AND LESSONS ROUTES *****

  get 'curriculum' => redirect('/courses')
  get 'courses' => 'courses#index'

  # Explicitly redirect deprecated routes (301)
  get 'courses/:course_name' => redirect('/%{course_name}')
  get 'courses/:course_name/lessons' => redirect('/%{course_name}')
  get 'courses/:course_name/lessons/:lesson_name' => redirect('/%{course_name}/%{lesson_name}')

  # Match all undefined routes as courses and/or lessons
  get ':course_name' => 'lessons#index', :as => "course"
  get ':course_name' => 'lessons#index', :as => "lessons"
  get ':course_name/:lesson_name' => 'lessons#show', :as => "lesson"


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @navbar = false
    @is_home_page = true
  end

  def about
  end
  
  def studygroups
  end

  def legal
  end

  def tou
  end

  def cla
  end

  # For the suggestion form in the footer
  def suggestion
    if user_signed_in?
      user = current_user.email
    else
      user = "< not logged in >"
    end

    if params[:suggestion]
      ContactMailer.suggestion_email(params[:suggestion], params[:pathname], user).deliver!
    end
    respond_to do |format|
      format.json { render json: params[:suggestion] }
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_sg_starting_one.html.erb
 <div class="studygroup-side pull-left" >
  <h3>Starting Your Own</h3>

  <p>
    These study groups are pretty ad-hoc -- they are run by students.  If you'd like to start one, you're welcome to cover any material you want at any pace you want.
  </p>
  <p>
    For instance, you could set up a daily Ruby study group that covers any questions people have about Ruby or you could have a weekly group that marches through the Javascript course at your own pace.  Regardless, if you let us know about your study group, we'll help get the word out for you.  We've included several of the previous study groups here so you can see what path they took.
  </p>
  <p>
    <strong>Option 1:</strong> Start a group on <a href="http://www.meetup.com">Meetup.com</a> (or any other site) in your local area and let us know about it.  We'll list it above.
  </p>
  <p>
    <strong>Option 2:</strong> Start a virtual group.  You can do this by using <a href="http://www.meetup.com/Learn-Web-Development/">our Meetup Group</a>. We'll make you an organizer and you can post your events on the group. 
  </p>
  <p>
    <strong>Option 3:</strong> Start a group through these tabs.  This option is described here.
  </p>

  <h3>How it works</h3>

  <p>
    Each study group has its own tab on this /studygroups page (as you can see) and each of these tabs is maintained by the leader of that study group. 
  </p>
  <p>
    So if you want to lead a study group, just fork this project and create your own tab, then submit it as a pull request to the `dev` branch of the main repo.  It's the same flow (though less intense) that we describe in the <%= link_to "Contributing section", contributing_path %>.
  </p>
  <p>
    You should be able to cut and paste code from the other tabs.  This is currently just one giant HTML file.  
  </p>
  <p>
    Disclaimer: This isn't the best way to do things, but we're still figuring out what we'll need to actually build in the future :)
  </p>
</div>


<div class="studygroup-content pull-left" >
  <h3>Leading a Study Group FAQ</h3>
    
  <ul>
    <li><strong>
      Why do people start these groups?
    </strong></li>
    <li>
      So far, the biggest reason has been so the leader can motivate him/herself to go through the material.  A nice side benefit is having other people to bounce questions off of.
    </li>
    <li><strong>
      What topics should I cover?
    </strong></li>
    <li>
      Anything you want! You could start in the middle, at the beginning, in the projects... if it's useful material to you, then it'll probably be useful for someone else too.
    </li>
    <li><strong>
      How often should we meet?
    </strong></li>
    <li>
      As often as you want.  Weekly seems to be good based on the groups so far.
    </li>
    <li><strong>
      How much code do I need to know?
    </strong></li>
    <li>
      Not much.  As an organizer, you just need to be able to edit this HTML page to keep your group schedule current from week-to-week.  As for the material itself that you'll be covering, you could already know it and offer to help people who don't or you could be learning it yourself at the same time.
    </li>
    <li><strong>
      How long do I need to lead the group?
    </strong></li>
    <li>
      As long as you want, though please give your students notice if you'll be discontinuing it (and remove its tab from this page).
    </li>
    <li><strong>How do I set up the video hangout?</strong></li>
    <ol>
      <li>Join our <%= link_to "Google Group", "https://plus.google.com/u/0/communities/100013596437379837846" %>, where we keep up with the development of this whole project.</li>
      <li>Set up a <%= link_to "Google Hangout on Air", "https://plus.google.com/hangouts/onair" %> and invite our google group ("Team Odin").  When you create the Hangout on Air, it will also create a Google Event for whenever you've scheduled the Hangout on Air</li>
      <li>Include the link to that Event in your study group tab (see the examples on other tabs, which have a link to each week's session)</li>
      <li>When it's time, "start" the Hangout on Air from the Event page.  It will take you to the Hangout window.  If you're in the Chrome browser (not Safari), you'll see an address bar at the top with the link to that Hangout.  Copy and paste that link into the Google Event page comments so everyone else in your group can join you.  Sometimes people may need to log out then try to follow the link (I don't know why).</li>
      <li>When you're ready to get started, click the "Start Broadcast" button from within the Hangout to begin broadcasting.  It will save the whole thing to your YouTube account when you're done.</li>
      <li>Cover your material, assign homework, and update your tab with the next week's links/assignments.  You can save time by scheduling events and Hangouts weeks in advance.</li>
    </ol>
  </ul>
  <p><em>If you have additional questions, please reach out to us as described on the <%= link_to "Contact Page", contact_path %></em></p>
  

  <p><strong>Stop by the <a href="https://plus.google.com/u/0/b/112041900311777032328/communities/100013596437379837846" target="_blank">
    Team Odin Google Community</a> anytime for help, support, or technical issues.  And have fun!</strong><br>
  </p>
            
</div>     <!-- .studygroup-content -->
<div style="clear:both"></div>

app/views/static_pages/cla.html.erb
<div class="StaticPagesController">
  <div class="container">

    <%= link_to "<< Back to Legal", legal_path %>

    <div id="cla">
      <% f = File.open("legal_cla.md", "rb") %>
      <%= md(f.read) %>
      <% f.close %>
    </div>

  </div>
</div>

app/views/static_pages/faq.html.erb
<div class="StaticPagesController">
  <div class="container">
    
    <h1>Frequently Asked Questions</h1>



    <h2 class="faq-question">Who Is This For?</h2>
    <p>
      This course is geared to absolute beginners and people who have maybe tried out different resources along the way but never really found anything worth sticking with long enough to become an expert in it.  Whether your ultimate goal is to work as a web developer, do freelancing, build a startup, or just hack together a homepage for yourself, you'll have the tools you need here.  
    </p>
    <p>
      We've built the curriculum with the most difficult of these cases in mind so it goes into a lot of depth.  This is on purpose -- a lot of existing "complete" resources actually only get you 10% of the way there and that's a problem.  They just aren't thorough.  That said, anyone who doesn't want to get quite so deep will have no problem skimming through lessons to pick up what they need to.
    </p>



    <h2 class="faq-question">What's the Goal of the Project?</h2>
    <p>
      The goal is to provide a complete path for students to go from zero to employed as web developers while working with other students along the way.  And that's just the beginning.
    </p>


    <h2 class="faq-question">How Long Does it Take?</h2>
    <p>
      We won't have any of this "Learn it all in two days!" BS.  You can't start from scratch and learn true web development in such a short period of time and you know it.  It's *highly* unlikely that you'll be employable after a weekend workshop or a one-month part-time course.  
    </p>
    <p>
      On the other hand, you don't necessarily need to put in 4 years getting a CS degree.  80% of what they cover won't be used during a typical web developer's early career and it's not necessary to know it to get hired.  So why not learn the 20% and learn the rest while you're getting paid on the job?
    </p>
    <p> 
      We've essentially distilled down what you most need to learn to hit that employable level, but it's still a healthy dose of learning.  Depending how fast you are, it will still take roughly 1000 hours of work to hit that sweet spot.  If you're naturally more technical or come from a technical background, it may be a bit faster.  If you're less technical or brand new to all this, it will take longer.  Don't despair!  When you think about it, that's pretty much the same learning curve you had to climb to learn anything worthwhile so far in life.  
    </p>
    <p>
      If you're doing it 40 hours a week, that's about 6 months.  If you're super intense, you can do it in 3.  If you're part-timing or less, you'll need to space it out over about a year.  That's just the reality of it.
    </p>
    <p>
      To make the best use of your time, try to set aside long blocks at once.  It can be difficult to find the time in your life, but you are significantly more productive when you can "get in the zone" and flow, which typically means setting aside 4-6 hours at a time, especially when building the projects.  You lose a significant portion of your efficiency if you try to do all your work in tiny chunks, where most of that time is spent just getting back in the right mindset.
    </p>



    <h2 class="faq-question">What Are You Actually Teaching?</h2>

    <p>
      We assume that you're at square one, so we start out by going over what exactly a web developer does, how to install the necessary software on your machine, and how to pair up with other students on projects in <%= link_to "Introduction to Web Development", course_path("introduction-to-web-development") %>.
    </p>

    <p>
      The <%= link_to "Web Development 101 course", course_path("web-development-101") %> will give you a chance to explore several of the languages and technologies you'll need to know on your journey so you have a good sense of context when you push forward into the real meaty stuff. It gives you a taste of HTML, CSS, Javascript, Ruby, Rails, databases, Git, testing and more. We've also created "mini-projects" that will give you a chance to test your new knowledge by actually building something (ideally with another student!).
    </p>

    <p>
      The curriculum takes a back-to-front approach to learning a Ruby on Rails workflow. That means starting with a <%= link_to "strong foundation in Ruby", course_path("ruby-programming") %> and an understanding of databases before migrating into Ruby on Rails (which is a framework built using Ruby).
    </p>


    <p>
      Next we move into in-depth understanding of HTML and CSS, Javascript, JQuery, and Backbone to give you the tools necessary to make them come alive by looking good, flowing well, and loading quickly. Along the way, you'll learn Git and deployment so you can build your portfolio, collaborate with others, and see your work on the web.
    </p>

    <p>
      Finally, we'll tackle more substantial project work and learn how to deal with legacy codebases and open-source projects. We'll also do some topical deep dives and cover areas specifically intended to help you when you're looking for jobs. Most of the back end of the curriculum is still under construction, so let us know if you'd like to help!
    </p>



    <h2 class="faq-question">Why Ruby on Rails?</h2>
    <p>
      Why not? There are dozens of possible frameworks and technology stacks out there to choose from and, frankly, they do pretty much the same things. Rails is attractive because it's a relatively straightforward and very well documented framework that's used by tons of great startups and tech companies today and it has a very strong community of developers and students who support it. 
    </p>
    <p>
      Rails lets you put up a functioning website in hours not days or weeks. The "in" tech will probably be something completely different in a few years, but Rails presents a great platform on which to build the skills you need to carry you to that next phase.
    </p>



    <h2 class="faq-question">Who is "Odin"?</h2>
    <p>
      Odin is a figure from Norse mythology, the allfather of the gods. He is portrayed as powerful and fickle (as they often are) but also wise and cunning. His search for knowledge is a thing of legends -- he <%= link_to "gave his eye for the wisdom of ages", "http://norse-mythology.org/tales/why-odin-is-one-eyed/" %> and hung from the world tree, pierced by his own spear, for nine days and nights to <%= link_to "gain the knowledge of runes", "http://norse-mythology.org/tales/odins-discovery-of-the-runes/" %>.
    </p>
    <p>
      Learning development is not an easy task and the tools laid out here are merely the path; you must walk it yourself. Should you possess a thirst for knowledge and persistence of spirit akin to that storied in Odin's mythos, you will find success on your journey.
    </p>
    <div class="odin-image">
      <%= image_tag "odin_logo_circle_black.gif", :width => 128 %>
    </div>


    <h2 class="faq-question">Where do I sign up for a course?</h2>
    <p>
      You don't have to!  Just dive right in, the content is free and available.  It'd be best if you started from the beginning and went through in order, but everyone's goals are different so we made the full curriculum available if you want to cherry-pick lessons or projects.

      That's not to say we will never have any sort of signup program (though if we do the core content here will remain free).  But right now what you see is what you get.  If you'd like to participate with a group of fellow students, check out (or start!) one of our <%= link_to "Study Groups", studygroup_path %>.
    </p>

    <h2 class="faq-question">But when do I have to pay for stuff?</h2>
    <p>
      You don't! 
    </p>


    <h2 class="faq-question">How is the Project Funded?</h2>
    <p>
      Goodwill and infinite patience.  Seriously, if you want to help, please <%= link_to "reach out", contact_path %>.
    </p>

    <h2 class="faq-question">But How Will You Become Sustainable?</h2>
    <p>
      Down the road, we want to keep our business model totally aligned with the ideal of educating lots of students very well.  Core content will always be free, but we'd also like to give students who want more structure and help on their journeys access to those services, which would be at a premium. 
    </p>
    <p>
      For a more detailed look at our business model, please watch <a href="http://www.youtube.com/watch?v=tO5sxLapAts">this video</a>.
    </p>

    <h2 class="faq-question">Can I Use This Curriculum To Teach?</h2>
    <p>
      This project is in two pieces -- the Curriculum and the Main Website which pulls it in.  The Main Website is a fully open-source project <a href="https://github.com/TheOdinProject/theodinproject/blob/master/license.txt">under an MIT license, so you can use any code you see there for whatever you want.</a>  The Curriculum is currently licensed under a <a href="https://github.com/TheOdinProject/curriculum/blob/master/license.md">Creative Commons license</a> that restricts it to noncommercial use without prior authorization.  
    </p>
    <p>
      That means you can use it to teach at your club, at your meetup, or with your friends.  In fact, we'd love it if you did that (and told us how it went!).  But you can't go out and use it to start a bootcamp without having a conversation first.  We're friendly and believe in widespread education -- reach out with any questions to <a href="mailto: contact@theodinproject.com">contact@theodinproject.com</a>.
    </p>

    <h2 class="faq-question">How Can I Get In Touch?</h2>

    <p>
      If you have questions about The Odin Project itself, check out our <%= link_to "Contact Page", contact_path %>.
    </p>


  </div>
</div>

app/views/static_pages/home.html.erb
<div id="home-page">

  <div class="above-the-fold">
    <div class="shield">
      <div class="navbar">
        <div class="nav-narrow">
          <div class="logo-wrapper">
            <%= render :partial => "shared/logo_text" %>
          </div>
          <div class="menu-wrapper">
            <%= link_to "Curriculum", courses_path(:ref => "homenav") %> |
            <% if current_user %>
              <%= link_to "Logout", logout_path(:ref => "homenav") %>
            <% else %>
              <%= link_to "Login", login_path(:ref => "homenav")%>
            <% end %>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
      <div class="container narrow">
        <div class="top-box-wrapper">
          <div class="top-box">
            <div class="headline">
              <h1>
                Learn Web Development for Free
              </h1>
            </div>
            <div class="subheading">
              <h2>
                Stop wasting time...&nbsp;  Here's what you need to know.
              </h2>
            </div>
          </div>
        </div>

        <div class="cta-box-top-wrapper">
          <div class="cta-box-top">
            <%= link_to lesson_path("introduction-to-web-development" ,"what-a-web-developer-does", :ref => "home") do %>
              <button class="btn btn-success cta-button">
                Learn what a web developer does
              </button>
            <% end %>
            <%= link_to courses_path(:ref => "home") do %>
              <button class="btn btn-success cta-button">
                Explore the full curriculum
              </button>
            <% end %>
            <p>
              ...or scroll down to learn more
            </p>
          </div>
        </div>

      </div>
    </div>
  </div>


  <div class="social-buttons">
    <div class="container narrow">
      <%= render "shared/social" %>
    </div>
  </div>

  <div class="what-its-about section">
    <div class="container narrow">

      <h2>Okay, what's this all about?</h2>
      <h4>
        Basically, this is the website we wish we'd had when we were learning on our own.  So we stitched together a curriculum from the best resources we could find online and here it is. This project is about:
      </h4>

      <div class="about-panels">

        <div class="about-panel">
          <div class="img-wrapper">
            <%= image_tag "icons/compass2.png", :width => "100px", :title => "A Path Forward" %>
          </div>
          <h3>
            Having a Path
          </h3>
          <p>
            This is a proven path to successfully learn web development so you don't have to wonder if you're doing the right stuff or wasting your time.
          </p>
        </div>

        <div class="about-panel">
          <div class="img-wrapper">
            <%= image_tag "icons/portfolio2.png", :width => "100px", :title => "Building a Portfolio" %>
          </div>
          <h3>
            Building a Portfolio
          </h3>
          <p>
            The best way to learn and get hired is to have a portfolio of work so we've laid out great projects to build along the way
          </p>
        </div>

        <div class="about-panel">
          <div class="img-wrapper">
            <%= image_tag "icons/chat.png", :width => "100px", :title => "Learning Together" %>
          </div>
          <h3>
            Learning Together
          </h3>
          <p>
            We make it easy to find and work with other learners so you don't have to go it alone anymore.
          </p>
        </div>

        <div class="clearfix"></div>

      </div>
    </div>
  </div>


  <div class="what-youll-learn dark">
    <div class="section">

      <div class="container narrow">

        <h2>
          What You'll Learn
        </h2>

        <div class="course-panels">

          <a href="<%= course_path('introduction-to-web-development') %>">
            <div class="course-panel p1">
              <div class="img-wrapper">
                <%= image_tag "icons/play.ico", :width => "80px", :title => "Introduction to Web Development" %>
              </div>

              <div class="copy-wrapper">
                <h3>
                  Introduction to Web Development
                </h3>
                <p>
                  A brief introduction to the practice and career of web development
                </p>
              </div>
              <div class="clearfix"></div>
            </div>
          </a>

          <a href="<%= course_path('web-development-101') %>">
            <div class="course-panel p2">
              <div class="img-wrapper">
                <%= image_tag "icons/web_development.png", :width => "80px", :title => "Web Development" %>
              </div>

              <div class="copy-wrapper">
                <h3>
                  Web Development 101
                </h3>
                <p>
                  Learn the basics of all the technologies you need to build websites
                </p>
              </div>
              <div class="clearfix"></div>
            </div>
          </a>

          <a href="<%= course_path('ruby-programming') %>">
            <div class="course-panel p3">
              <div class="img-wrapper">
                <%= image_tag "icons/ruby.png", :width => "65px", :title => "Ruby Programming" %>
              </div>

              <div class="copy-wrapper">
                <h3>
                  Ruby Programming
                </h3>
                <p>
                  Learn programming fundamentals in Ruby, the language built for programmer happiness
                </p>
              </div>
              <div class="clearfix"></div>
            </div>
          </a>

          <a href="<%= course_path('ruby-on-rails') %>">
            <div class="course-panel p4">
              <div class="img-wrapper">
                <%= image_tag "icons/rails.png", :width => "80px", :title => "Ruby on Rails" %>
              </div>

              <div class="copy-wrapper">
                <h3>
                  Ruby on Rails
                </h3>
                <p>
                  Learn to rapidly develop and deploy websites using Ruby on Rails
                </p>
              </div>
              <div class="clearfix"></div>
            </div>
          </a>

          <a href="<%= course_path('html5-and-css3') %>">
            <div class="course-panel p5">
              <div class="img-wrapper">
                <%= image_tag "icons/html5.png", :width => "80px", :title => "HTML5 and CSS3" %>
              </div>

              <div class="copy-wrapper">
                <h3>
                  HTML5 and CSS3
                </h3>
                <p>
                  Dive deeper and understand how to really make your websites look good
                </p>
              </div>
              <div class="clearfix"></div>
            </div>
          </a>

          <a href="<%= course_path('javascript-and-jquery') %>">
            <div class="course-panel p6">
              <div class="img-wrapper">
                <%= image_tag "icons/javascript2.png", :width => "80px", :title => "Javascript and jQuery" %>
              </div>

              <div class="copy-wrapper">
                <h3>
                  Javascript and jQuery
                </h3>
                <p>
                  Make your websites dynamic and smooth with Javascript and jQuery
                </p>
              </div>
              <div class="clearfix"></div>
            </div>
          </a>

          <a href="<%= course_path('getting-hired-as-a-web-developer') %>">
            <div class="course-panel p7">
              <div class="img-wrapper">
                <%= image_tag "icons/job_button2.png", :width => "80px", :title => "Getting Hired as a Web Developer" %>
              </div>

              <div class="copy-wrapper">
                <h3>
                  Getting Hired as a Web Developer
                </h3>
                <p>
                  You've got the skills and the portfolio, now how do you get the job?
                </p>
              </div>
              <div class="clearfix"></div>
            </div>
          </a>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="how-it-works section">
    <div class="container narrow">
      <h2>How it Works</h2>
      <div class="clearfix"></div>
      <div class="panel-wrapper">
        <div class="panel">
          <div class="img-wrapper">
            <%= image_tag "learn_online3.jpg", :width => "300px", :height => "150px", :title => "Learn to Code" %>
          </div>
          <h3>
            Learn
          </h3>
          <p>
            We'll guide you through the best videos, tutorials, blog posts, and courses on the web for learning each subject.
          </p>
        </div>

        <div class="panel">
          <div class="img-wrapper">
            <%= image_tag "writing_code2.jpg", :width => "300px", :height => "150px", :title => "Write Code" %>
          </div>
          <h3>
            Build
          </h3>
          <p>
            You will build dozens of projects along the way, from simple scripts to full programs and deployed websites
          </p>
        </div>

      </div>

      <div class="work-together">
        <div class="img-wrapper">
            <%= image_tag "work_together_blur.jpg", :width => "500px", :height => "200px", :title => "Work Together" %>
        </div>
        <div class="copy-wrapper">
          <h3>
            Work with Other Students
          </h3>
          <p>
            Learning on your own sucks (we've been there).  We're building tools to connect you with other students along the way so you can pair up on the projects or just work through those annoying bugs with someone else across the world.
          </p>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>

  <div class="why-awesome section dark">
    <div class="container narrow">
      <h2>
        Why This Project Rocks
      </h2>
      <div class="panel-wrapper">
        <div class="panel">
          <div class="img-wrapper">
            <%= image_tag "icons/textedit.png", :width => "150px", :title => "A Living Curriculum" %>
          </div>
          <h3>
            The Curriculum Lives
          </h3>
          <p>
            The curriculum is really flexible -- when a better way to learn something comes along we can just use that instead!
          </p>
          <a href="https://github.com/TheOdinProject/curriculum">See the curriculum on Github >></a>
        </div>

        <div class="panel">
          <div class="img-wrapper">
            <%= image_tag "icons/open_source2.svg", :width => "150px", :title => "Open Source" %>
          </div>
          <h3>
            It's Open Source
          </h3>
          <p>
            This website is available under an MIT license and the curriculum is Creative Commons.  Both are on Github.          </p>
          <a href="https://github.com/TheOdinProject/theodinproject">See this site on Github >></a>
        </div>

        <div class="panel">
          <div class="img-wrapper">
            <%= image_tag "icons/xcode.png", :width => "150px", :title => "Build You Own Tools" %>
          </div>
          <h3>
            Build Your Own Tools
          </h3>
          <p>
            Students are currently contributing to both the curriculum and the main website... so they build what they use.
          </p>
          <%= link_to "Learn how to contribute >>", contributing_path %>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>

    <div class="clear-div"></div>

  <div class="cta-bottom section">
    <div class="container narrow">
      <p>
        Are you curious yet?
      </p>
      <%= link_to courses_path(:ref => "home_b") do %>
        <button class="btn btn-success cta-button">
          Check out the curriculum!
        </button>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/legal.html.erb
<div class="StaticPagesController">
  <div class="container">
    
    <h1>Legal Stuff</h1>

    <p>...Because otherwise what would we do with all the lawyers?!?</p>

    <%= link_to tou_path do %>
      <h2>Terms of Use</h2>
    <% end %>
    <p>
      These Terms of Use govern your use of the website.
    </p>


    <%= link_to cla_path do %>
      <h2>Contributor Licensing Agreement (CLA)</h2>
    <% end %>
    <p>
      This agreement applies when you make contributions to this website.  For details about contributions to the Curriculum, refer to the <%= link_to "Contributing section", contributing_path %>.
    </p>

  </div>
</div>