config/routes.rb
Theodinproject::Application.routes.draw do
devise_for :users, 
  :controllers => { :registrations => "registrations", 
    :omniauth_callbacks => "omniauth_callbacks",
    :confirmations => "confirmations" }
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy', :method => :delete
    get 'sign_up' => 'devise/registrations#new'
    get 'signup' => 'devise/registrations#new'
    get '/confirm_email' => 'users#send_confirmation_link'
  end

  root :to => 'static_pages#home'
  get 'home' => 'static_pages#home'
  get 'scheduler' => redirect('/courses')
  post 'thank_you' => 'static_pages#send_feedback'
  post 'suggestion' => 'static_pages#suggestion'
  get 'students' => 'users#index'
  get 'about' => "static_pages#about"
  get 'faq' => "static_pages#faq"
  get 'contact' => "static_pages#contact"
  get 'contributing' => "static_pages#contributing"
  get 'studygroup' => redirect('/studygroups')
  get 'legal' => "static_pages#legal"
  get 'cla' => "static_pages#cla"
  get 'tou' => "static_pages#tou"
  get 'press' => redirect('https://docs.google.com/document/d/1FmjfYvOsQ-syoOCzuvPXv96TCxeJAT9m-Wl7trgNZcE/pub')
  get 'studygroups' => "static_pages#studygroups"

  #failure route if github information returns invalid
  get '/auth/failure' => 'omniauth_callbacks#failure'


  resources :cal_events

  # This is being hidden until needed (it was needed by the scheduler
  # but that got killed but will still be useful later)
  # resource :user_pref, :only => [:edit, :update]

  resources :users, :only => [:show, :index, :edit, :update] do
    resource :contact, :only => [:new, :create]
  end

  resources :splash_emails, :only => [:create]

  resource :forum, :only => [:show]

  post 'lesson_completions' => 'lesson_completions#create'
  delete 'lesson_completions/:lesson_id' => 'lesson_completions#destroy', :as => "lesson_completion"

  # Sitemap
  get "sitemap" => "sitemap#index", :defaults => { :format => "xml" }

  # ***** COURSES AND LESSONS ROUTES *****

  get 'curriculum' => redirect('/courses')
  get 'courses' => 'courses#index'

  # Explicitly redirect deprecated routes (301)
  get 'courses/:course_name' => redirect('/%{course_name}')
  get 'courses/:course_name/lessons' => redirect('/%{course_name}')
  get 'courses/:course_name/lessons/:lesson_name' => redirect('/%{course_name}/%{lesson_name}')

  # Match all undefined routes as courses and/or lessons
  get ':course_name' => 'lessons#index', :as => "course"
  get ':course_name' => 'lessons#index', :as => "lessons"
  get ':course_name/:lesson_name' => 'lessons#show', :as => "lesson"


end

app/views/shared/_admin_flash.html.erb
<% AdminFlash.showable_messages(disabled_flash_ids_from_cookies).each do |m|  %>
  <div class="alert alert-warning alert-dismissable admin-flash-message">
    <p>
      <button type="button" id="close_admin_flash_<%= m.id %>" data-exp="<%= m.expires %>" data-id="<%= m.id %>" class="close" aria-hidden="true" >&times;</button>
    </p>
    <div class="admin-flash-text">
      <%= md(m.message) %>
    </div>  
  </div>
<% end %>

app/views/shared/_complete_lesson.html.erb
<!--
This partial displays the section at the bottom of the page where a user can mark
a lesson completed or not completed.  It will also be rendered with the unobtrusive
javscript that is used with the AJAX form which allows the user to do the checking
and unchecking 
(so once on initial page load and again any time the user clicks the
checkbox).
-->
  
  <% if user_signed_in? %>
  
    <% if current_user.completed_lesson?(@lesson) %>

      <div class="checkbox-container lc-checked">

        <h3>
          <%= @lesson.is_project ? "Project" : "Lesson" %> Completed
        </h3>
      </div>  
      <%= form_tag lesson_completion_path(:lesson_id => @lesson.id), :method => "DELETE", :remote => true, :class => "lc-link-form" do %>
        <%= link_to "Change #{@lesson.is_project ? 'project' : 'lesson'} to not completed", "#", :class => "lc-uncomplete-link" %>
      <% end %>
    <% else %>

      <%= form_for LessonCompletion.new, :method => "POST", :remote => true do |f| %>
        <a href="#" class="checkbox-container lc-unchecked">
          <%= hidden_field_tag(:lesson_id, @lesson.id) %>
          <h3>
            Mark <%= @lesson.is_project ? "Project" : "Lesson" %> Completed
          </h3>
        </a>
      <% end %>

    <% end %>
  
  <% else %>

      <div class="checkbox-container lc-disabled">            
          <h3>
            Mark <%= @lesson.is_project ? "Project" : "Lesson" %> Completed
          </h3>
      </div>

    <%= link_to "Sign in to track your progress", login_path, :class => "lc-signin-link" %> 
  <% end %>
<div class="lc-hover"></div>
<div class="lc-waiting"></div>

app/views/shared/_disqus_forum.html.erb
<div id="disqus_thread"></div>
  <script type="text/javascript">
      /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
      var disqus_shortname = "<%= ENV['DISQUS_WEBSITE_NAME'] %>"; // required: replace example with your forum shortname

      /* * * DON'T EDIT BELOW THIS LINE * * */
      (function() {
          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
          dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
      $("document").ready(function() {
          setTimeout(function() {
              $("ul.galleria li:first-child img").trigger('click');
          },10);
       });
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

  <%= raw @discusjs %>

app/views/shared/_ga.html.erb
<!-- Google Analytics Tracking Snippet -->
<!-- Only load it if we're in a production environment! -->
  
  
<% if Rails.env.production? %>

  <script type="text/javascript">  
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-41005438-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>

<% else %>

  <script type="text/javascript">
    var _gaq = [];
  </script>

<% end %>

app/views/shared/_github_login_button.html.erb
<div class="row">
  <%- if @user.password_required? %>
    <div class="social-wrapper">
      <%- resource_class.omniauth_providers.each do |provider| %>
        <%= link_to "<i class=\"fa fa-#{provider} providers-button\"></i>#{screen} with #{provider.to_s.titleize}".html_safe, omniauth_authorize_path(resource_name, provider), class: 'btn btn-social btn-large btn-lg btn-github' %><br />
      <% end -%>
      <h3> ...or do it the old fashioned way: </h3>
    </div>
  <% end -%>
</div>

app/views/shared/_head.html.erb
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="The Odin Project empowers aspiring web developers to learn together">
    <meta name="keywords" content="learn web development, learn ruby on rails, ruby on rails, ruby, rails">
    <title><%= content_for?(:title) ? yield(:title) : title %></title>
    <%= csrf_meta_tags %>


    <!-- Grabbing the Open Sand Condensed web fonts from Google -->
    <!-- NOTE: THIS IS A MAJOR CAUSE OF PAGE SLOWNESS!!!  -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700,300italic|Open+Sans:300,300italic,400,700' rel='stylesheet' type='text/css'>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Pull in any custom style mods from subordinate layouts -->
    <style type="text/css"><%= yield :stylesheets %> </style>

    <!-- Javascripts
    ================================================== -->
    <!-- SHOULD BE Placed at the end of the document so the pages load faster BUT then my page-specific JS wouldn't run -->
    <%= javascript_include_tag "application" %>

    <%= render "shared/ga" %>

    <!-- Include the moot.it forums code if we're on the forums page -->
    <% if @is_forum %>
        <!-- (1) Optimize for mobile versions: http://goo.gl/EOpFl -->
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <!-- (1) force latest IE rendering engine: http://goo.gl/tf4JH -->
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <% end %>

  </head>

app/views/shared/_lc_index.html.erb
<!--
This partial displays the checkbox at the left of a lesson on the index page
It will also be rendered with the unobtrusive javascript that is used with the 
AJAX form which allows the user to do the checking and unchecking 
(so once on initial page load and again any time the user clicks the
checkbox).
-->

<!-- ...needed because sometimes it will be called as a partial
     and sometimes it will be rendered using the EJS -->
<% lesson ||= @lesson %>

  <% if current_user.completed_lesson?(lesson) %>
  
    <%= form_tag lesson_completion_path(:lesson_id => lesson.id), :method => "DELETE", :remote => true do %>
      <a href="#" class="lc-checkbox lc-checked" title="Uncheck to mark lesson not completed">
      </a>
    <% end %> 
  
  <% else %>
  
    <%= form_for LessonCompletion.new, :method => "POST", :remote => true do |f| %>
      <a href="#" class="lc-checkbox lc-unchecked"  title="Check to mark lesson completed">
        <%= hidden_field_tag(:lesson_id, lesson.id) %>
      </a>
    <% end %> 
  
  <% end %>

app/views/shared/_logo_text.html.erb
<div class="brand-box">
  <a href=<%= home_url %>>
    <%= image_tag "odin_head_silhouette_2_circle_simple_transparent.gif", :class=>"logo-img" %>
    <span class="logo-text">
      The Odin Project
    </span>
    <span class="beta-tag">
      beta
    </span>
  </a>
</div>

app/views/shared/_navbar.html.erb
    <div class="navbar navbar-fixed-top" id="top-navbar">


      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= render "shared/logo_text" %>
          <div class="container nav-collapse">
            <ul class="nav pull-right nav-links">
              <li class="top-link nav-search"><%= render "shared/search_box" %></li>              
              <li class="top-link"><a href="<%= curriculum_path %>">Curriculum</a></li>
              <% if user_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><strong><%= current_user.username %> <b class="caret"></b></strong></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Forum", forum_path %></li>
                    <li><%= link_to "Study Groups", studygroup_path %></li>
                    <li><%= link_to "Students", students_path %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Account", edit_user_registration_path %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Logout", logout_path  %></li>
                  </ul>
              <% else %>
                <li data-no-turbolinks><%= link_to "Login", login_path, :class=>"top-link", :id=>"login-link" %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

app/views/shared/_pagination.html.erb
<!-- already creates a div with class "pagination" -->
<div class="pagination-wrapper">
  <%= will_paginate collection %>
</div>

app/views/shared/_pt_bar.html.erb
<!--  This bar allows users who are signed in to view their progress
      as they move through a course.  It is generated totally
      using CSS and HTML (instead of Javascript) -->

<% if user_signed_in? %>
  <% lessons = lesson.course.lessons.order(:position => :asc) %>
  <% pct = (100.0 / (lessons.count + 1.0)).to_f %>
  <% course_pct = lesson.course.percent_completed_by(current_user) %>

  <div id="lc-progress-bar">
    <div class="lc-progress-wrapper">

      <!-- Beginning and end cap circles (clickable!) -->
      <%= link_to lessons_path(lesson.course.title_url, :ref => "lc-pb") do %>
        <div  class="lc-end-circle <%= course_pct == 100 ? 'lc-completed' : '' %>" 
              title="Go back to <%= lesson.course.title %>"
              style="0%">
        </div>
      <% end %>
      <%= link_to lessons_path(lesson.course.title_url, :ref => "lc-pb") do %>
        <div  class="lc-end-circle lc-right-end <%= course_pct == 100 ? 'lc-completed' : '' %>" 
              title="Go back to <%= lesson.course.title %>"
              style="0%">
        </div>
      <% end %>

      <!-- Individual lesson circles (clickable!) -->
      <% lessons.each_with_index do |l,i| %>
        <% if l == lesson %>
          <div class="pending-line"></div>
          <div class="completed-line" style="width: <%= (i+1) * pct %>%"></div>
          <%= link_to "#" do %>
            <div  class="lc-active-circle" 
                  title="You've completed <%= course_pct.to_i %>% of this course"
                  style="left:<%= (i+1)*pct %>%">
              <span class="lc-pct"><%= course_pct.to_i %>%</span>
            </div>
          <% end %>
        <% else %>
          <% classes =  "lc-circle" %>
          <% classes <<  ( current_user.completed_lesson?(l) ? ' lc-complete' : ' lc-pending' ) %>
          <% classes << ( l.is_project ? ' lc-project' : ' lc-lesson' ) %>
          <%= link_to lesson_path(l.course.title_url, l.title_url, :ref => "lc-pb") do %>
            <div  class="<%= classes %>" 
                  title="<%= l.is_project ? "Project:" : "" %> <%= l.title %>"
                  style="left:<%= (i+1)*pct %>%">
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

<% end %>

app/views/shared/_search_box.html.erb
<form>
  <input type="text" id="st-search-input" class="st-search-input" />
</form>
<script type="text/javascript">
    var Swiftype = window.Swiftype || {};
    
    (function() {

      Swiftype.renderStyle = 'inline';            // Tell swiftype we don't want their default modal
      /** DO NOT EDIT BELOW THIS LINE **/
      var script = document.createElement('script'); script.type = 'text/javascript'; script.async = true;
      script.src = "//s.swiftypecdn.com/embed.js";
      var entry = document.getElementsByTagName('script')[0];
      entry.parentNode.insertBefore(script, entry);
    }());  
</script>

app/views/shared/_search_results.html.erb
<div id="search-results-modal" class="modal hide fade" data-backdrop="static">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Search Results</h3>
  </div>
  <div id="st-results-container" class="modal-body" >
  </div>
  <div class="modal-footer">
    <a class="btn" id="search-results-close" data-dismiss="modal" aria-hidden="true">Close</a>
  </div>
</div>

app/views/shared/_social_sharing_buttons.html.erb
<div class="social_sharing_buttons pull-left">
  <!-- Twitter Button -->
  <%= link_to raw('<span class="fa fa-twitter-square"></span>'), "https://twitter.com/share?text=Check out this lesson: #{@lesson.title}", :data => {toggle: 'tooltip'}, title: "Tweet this lesson" %>
  <!-- Facebook Button -->
  <%= link_to raw('<span class="fa fa-facebook-square"></span>'),
    "https://www.facebook.com/dialog/share?app_id=1391239864499204&href=#{request.original_url}&redirect_uri=#{request.original_url}", :data => {toggle: 'tooltip'}, title: "Share on Facebook" %>
  <!-- Google+ Button -->
  <a data-toggle="tooltip" title="Share on Google+" href=<%="https://plus.google.com/share?url=#{request.original_url}"%>><span class="fa fa-google-plus-square"></span></a>
  <!-- Pinterest Button -->
  <a data-toggle="tooltip" title="Pin this lesson" href=<%="//www.pinterest.com/pin/create/button/?url=#{request.original_url}&media=#{image_url('odin_big_silhouette.gif')}&description=#{url_format(@lesson.title)}"%> target="__blank"><span class="fa fa-pinterest-square"></span></a>
</div>